version: 2
updates:
- package-ecosystem: pip
  directory: "/etc"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: publicsuffixlist
    versions:
    - "> 0.6.13"
  - dependency-name: qrcodegen
    versions:
    - "> 1.2.0"
- package-ecosystem: pip
  directory: "/requirements"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: pip
  directory: "/libweasyl"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: misaka
    versions:
    - ">= 2.a"
    - "< 3"
