name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    container:
      image: ghcr.io/weasyl/ci-base-image@sha256:d6e6b99cb6c00bc5aaed1017ee389b9d18b12d39cae082c16e664ab20ff9e8b7
      options: --user 1001

    services:
      weasyl-database:
        image: postgres:9.6
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_USER: weasyl
          POSTGRES_DB: weasyl_test
        # probably ready by the time the tests run anyway; no need to add latency
        #options: >-
        #  --health-cmd pg_isready
        #  --health-interval 10s
        #  --health-timeout 5s
        #  --health-retries 5

      weasyl-memcached:
        image: memcached:1.5-alpine

    steps:
      - uses: actions/checkout@v3

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: cache-${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            cache-${{ runner.os }}-npm-

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: cache-${{ runner.os }}-pip-${{ hashFiles('etc/requirements.txt', 'requirements/test.txt', 'requirements/lxml.txt') }}
          restore-keys: |
            cache-${{ runner.os }}-pip-

      - name: Create virtualenv
        run: python3 -m venv --system-site-packages .venv

      - name: Install npm dependencies
        run: npm ci

      - name: Install pip dependencies
        run: .venv/bin/pip install -r etc/requirements.txt -r requirements/lxml.txt -r requirements/test.txt

      - name: Install libweasyl
        run: .venv/bin/pip install --no-deps -e libweasyl

      - name: Install Weasyl
        run: .venv/bin/pip install --no-deps -e .

      - name: Configure Weasyl
        run: |
          cp ci/site.config.txt config/
          cp config/weasyl-staff.example.py config/weasyl-staff.py
          printf %.8s "$GITHUB_SHA" > version.txt

      - name: Build assets
        run: node build.js

      - name: Test libweasyl
        env:
          WEASYL_TEST_SQLALCHEMY_URL: postgresql+psycopg2cffi://weasyl@weasyl-database/weasyl_test
        run: .venv/bin/coverage run -m pytest libweasyl.test libweasyl.models.test

      - name: Test weasyl
        env:
          WEASYL_APP_ROOT: .
          WEASYL_STORAGE_ROOT: testing
        run: .venv/bin/coverage run -m pytest weasyl.test

      - name: Create coverage report
        run: |
          .venv/bin/coverage combine
          .venv/bin/coverage xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
